fixes and workarounds

diff --git a/scripts/build-vendor b/scripts/build-vendor
--- a/scripts/build-vendor
+++ b/scripts/build-vendor
@@ -19,18 +19,18 @@ factory_dir="${vendor_dir}/${device}/${factory_build}"
 
 mkdir -p "${download_dir}" "${factory_dir}" "${vendor_out}"
 
+# TODO: disabled manual download because OTA needs to be downloaded in addition to factory at moment
 # Fetch/extract proprietary blobs
-if [ ! -f "${factory_dir}/${factory_file}" ]; then
-	wget "${factory_url}/${factory_file}" -O "${download_dir}/${factory_file}"
-	file_hash="$(sha256sum "${download_dir}/${factory_file}" | cut -c1-64)"
-	[[ "${factory_hash}" == "$file_hash" ]] || \
-		{ ( >&2 echo "Invalid hash for ${factory_file}" ); exit 1; }
-	mv "${download_dir}/${factory_file}" "${factory_dir}/${factory_file}"
-fi
+# if [ ! -f "${factory_dir}/${factory_file}" ]; then
+# 	wget "${factory_url}/${factory_file}" -O "${download_dir}/${factory_file}"
+# 	file_hash="$(sha256sum "${download_dir}/${factory_file}" | cut -c1-64)"
+# 	[[ "${factory_hash}" == "$file_hash" ]] || \
+# 		{ ( >&2 echo "Invalid hash for ${factory_file}" ); exit 1; }
+# 	mv "${download_dir}/${factory_file}" "${factory_dir}/${factory_file}"
+# fi
 "${base_dir}/vendor/android-prepare-vendor/execute-all.sh" \
 	--debugfs \
 	--yes \
-	--imgs "${factory_dir}/${factory_file}" \
 	--device "${device}" \
 	--buildID "${factory_build}" \
 	--output "${vendor_out}" \
